# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gist.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbtgen = QtWidgets.QPushButton(self.centralwidget)
        self.pbtgen.setGeometry(QtCore.QRect(60, 100, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbtgen.setFont(font)
        self.pbtgen.setObjectName("pbtgen")
        self.pdtstr = QtWidgets.QPushButton(self.centralwidget)
        self.pdtstr.setGeometry(QtCore.QRect(450, 90, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pdtstr.setFont(font)
        self.pdtstr.setObjectName("pdtstr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.numbers = QtWidgets.QLineEdit(self.centralwidget)
        self.numbers.setGeometry(QtCore.QRect(270, 0, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numbers.setFont(font)
        self.numbers.setObjectName("numbers")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 160, 301, 51))
        self.label_3.setObjectName("label_3")
        self.gr = QtWidgets.QGraphicsView(self.centralwidget)
        self.gr.setGeometry(QtCore.QRect(70, 200, 671, 341))
        self.gr.setObjectName("gr")
        self.znach = QtWidgets.QLabel(self.centralwidget)
        self.znach.setGeometry(QtCore.QRect(130, 250, 551, 211))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.znach.setFont(font)
        self.znach.setText("")
        self.znach.setObjectName("znach")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbtgen.setText(_translate("MainWindow", "сгенерировать"))
        self.pdtstr.setText(_translate("MainWindow", "построить"))
        self.label.setText(_translate("MainWindow", "введите числа"))
        self.label_2.setText(_translate("MainWindow", "нажмите чтобы сгенериваовать числа на рандом "))
        self.label_3.setText(_translate("MainWindow", "нажмите чтобы построить по вашим данным"))
