# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Vn = QtWidgets.QLabel(self.centralwidget)
        self.Vn.setGeometry(QtCore.QRect(40, 30, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Vn.setFont(font)
        self.Vn.setObjectName("Vn")
        self.phin = QtWidgets.QLabel(self.centralwidget)
        self.phin.setGeometry(QtCore.QRect(40, 110, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.phin.setFont(font)
        self.phin.setObjectName("phin")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(560, 70, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.Vnl = QtWidgets.QLineEdit(self.centralwidget)
        self.Vnl.setGeometry(QtCore.QRect(340, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Vnl.setFont(font)
        self.Vnl.setText("")
        self.Vnl.setObjectName("Vnl")
        self.phinL = QtWidgets.QLineEdit(self.centralwidget)
        self.phinL.setGeometry(QtCore.QRect(340, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.phinL.setFont(font)
        self.phinL.setObjectName("phinL")
        self.lblo = QtWidgets.QLabel(self.centralwidget)
        self.lblo.setGeometry(QtCore.QRect(270, 470, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblo.setFont(font)
        self.lblo.setText("")
        self.lblo.setObjectName("lblo")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(130, 190, 531, 341))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Vn.setText(_translate("MainWindow", "начальная скорость"))
        self.phin.setText(_translate("MainWindow", "начальный угол"))
        self.btn.setText(_translate("MainWindow", "Расчитать!"))
